//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceModelDataPasien
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceModelDataPasien.IServiceModelDataPasien")]
    public interface IServiceModelDataPasien
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getAllDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getAllDataPasienResponse")]
        ServiceModelDataPasien.getAllDataPasienResponse getAllDataPasien(ServiceModelDataPasien.getAllDataPasienRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getAllDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getAllDataPasienResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.getAllDataPasienResponse> getAllDataPasienAsync(ServiceModelDataPasien.getAllDataPasienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByID", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDResponse")]
        ServiceModelDataPasien.getDataPasienByIDResponse getDataPasienByID(ServiceModelDataPasien.getDataPasienByIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByID", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByIDResponse> getDataPasienByIDAsync(ServiceModelDataPasien.getDataPasienByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDPendudukResponse")]
        ServiceModelDataPasien.getDataPasienByIDPendudukResponse getDataPasienByIDPenduduk(ServiceModelDataPasien.getDataPasienByIDPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByIDPendudukResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByIDPendudukResponse> getDataPasienByIDPendudukAsync(ServiceModelDataPasien.getDataPasienByIDPendudukRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByNIK", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByNIKResponse")]
        ServiceModelDataPasien.getDataPasienByNIKResponse getDataPasienByNIK(ServiceModelDataPasien.getDataPasienByNIKRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/getDataPasienByNIK", ReplyAction="http://tempuri.org/IServiceModelDataPasien/getDataPasienByNIKResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByNIKResponse> getDataPasienByNIKAsync(ServiceModelDataPasien.getDataPasienByNIKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/createDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/createDataPasienResponse")]
        ServiceModelDataPasien.createDataPasienResponse createDataPasien(ServiceModelDataPasien.createDataPasienRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/createDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/createDataPasienResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.createDataPasienResponse> createDataPasienAsync(ServiceModelDataPasien.createDataPasienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/updateDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/updateDataPasienResponse")]
        ServiceModelDataPasien.updateDataPasienResponse updateDataPasien(ServiceModelDataPasien.updateDataPasienRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/updateDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/updateDataPasienResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.updateDataPasienResponse> updateDataPasienAsync(ServiceModelDataPasien.updateDataPasienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/deleteDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/deleteDataPasienResponse")]
        ServiceModelDataPasien.deleteDataPasienResponse deleteDataPasien(ServiceModelDataPasien.deleteDataPasienRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPasien/deleteDataPasien", ReplyAction="http://tempuri.org/IServiceModelDataPasien/deleteDataPasienResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPasien.deleteDataPasienResponse> deleteDataPasienAsync(ServiceModelDataPasien.deleteDataPasienRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataPasien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllDataPasienRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<Tracking_Vaksin_Services.DataPasienS> dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public getAllDataPasienRequest()
        {
        }
        
        public getAllDataPasienRequest(System.Collections.Generic.List<Tracking_Vaksin_Services.DataPasienS> dataPasienS, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataPasienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllDataPasienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getAllDataPasienResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<Tracking_Vaksin_Services.DataPasienS> dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getAllDataPasienResponse()
        {
        }
        
        public getAllDataPasienResponse(bool getAllDataPasienResult, System.Collections.Generic.List<Tracking_Vaksin_Services.DataPasienS> dataPasienS, int StatusCode, string Message)
        {
            this.getAllDataPasienResult = getAllDataPasienResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByIDRequest()
        {
        }
        
        public getDataPasienByIDRequest(Tracking_Vaksin_Services.DataPasienS dataPasienS, int ID, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.ID = ID;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getDataPasienByIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByIDResponse()
        {
        }
        
        public getDataPasienByIDResponse(bool getDataPasienByIDResult, Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.getDataPasienByIDResult = getDataPasienByIDResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByIDPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByIDPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int IDPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByIDPendudukRequest()
        {
        }
        
        public getDataPasienByIDPendudukRequest(Tracking_Vaksin_Services.DataPasienS dataPasienS, int IDPenduduk, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.IDPenduduk = IDPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByIDPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByIDPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getDataPasienByIDPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByIDPendudukResponse()
        {
        }
        
        public getDataPasienByIDPendudukResponse(bool getDataPasienByIDPendudukResult, Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.getDataPasienByIDPendudukResult = getDataPasienByIDPendudukResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByNIK", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByNIKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NIK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByNIKRequest()
        {
        }
        
        public getDataPasienByNIKRequest(Tracking_Vaksin_Services.DataPasienS dataPasienS, string NIK, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.NIK = NIK;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPasienByNIKResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPasienByNIKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getDataPasienByNIKResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPasienByNIKResponse()
        {
        }
        
        public getDataPasienByNIKResponse(bool getDataPasienByNIKResult, Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.getDataPasienByNIKResult = getDataPasienByNIKResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDataPasien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDataPasienRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public createDataPasienRequest()
        {
        }
        
        public createDataPasienRequest(Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDataPasienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDataPasienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool createDataPasienResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public createDataPasienResponse()
        {
        }
        
        public createDataPasienResponse(bool createDataPasienResult, Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.createDataPasienResult = createDataPasienResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDataPasien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateDataPasienRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public updateDataPasienRequest()
        {
        }
        
        public updateDataPasienRequest(Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDataPasienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateDataPasienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool updateDataPasienResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPasienS dataPasienS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public updateDataPasienResponse()
        {
        }
        
        public updateDataPasienResponse(bool updateDataPasienResult, Tracking_Vaksin_Services.DataPasienS dataPasienS, int StatusCode, string Message)
        {
            this.updateDataPasienResult = updateDataPasienResult;
            this.dataPasienS = dataPasienS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDataPasien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteDataPasienRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public deleteDataPasienRequest()
        {
        }
        
        public deleteDataPasienRequest(int id, int StatusCode, string Message)
        {
            this.id = id;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDataPasienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteDataPasienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool deleteDataPasienResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public deleteDataPasienResponse()
        {
        }
        
        public deleteDataPasienResponse(bool deleteDataPasienResult, int StatusCode, string Message)
        {
            this.deleteDataPasienResult = deleteDataPasienResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceModelDataPasienChannel : ServiceModelDataPasien.IServiceModelDataPasien, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceModelDataPasienClient : System.ServiceModel.ClientBase<ServiceModelDataPasien.IServiceModelDataPasien>, ServiceModelDataPasien.IServiceModelDataPasien
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceModelDataPasienClient() : 
                base(ServiceModelDataPasienClient.GetDefaultBinding(), ServiceModelDataPasienClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceModelDataPasien.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPasienClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceModelDataPasienClient.GetBindingForEndpoint(endpointConfiguration), ServiceModelDataPasienClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPasienClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceModelDataPasienClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPasienClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceModelDataPasienClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPasienClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.getAllDataPasienResponse ServiceModelDataPasien.IServiceModelDataPasien.getAllDataPasien(ServiceModelDataPasien.getAllDataPasienRequest request)
        {
            return base.Channel.getAllDataPasien(request);
        }
        
        public bool getAllDataPasien(ref Tracking_Vaksin_Services.DataPasienS dataPasienS1, ref System.Collections.Generic.List<Tracking_Vaksin_Services.DataPasienS> dataPasienS, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.getAllDataPasienRequest inValue = new ServiceModelDataPasien.getAllDataPasienRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.getAllDataPasienResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).getAllDataPasien(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getAllDataPasienResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.getAllDataPasienResponse> getAllDataPasienAsync(ServiceModelDataPasien.getAllDataPasienRequest request)
        {
            return base.Channel.getAllDataPasienAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.getDataPasienByIDResponse ServiceModelDataPasien.IServiceModelDataPasien.getDataPasienByID(ServiceModelDataPasien.getDataPasienByIDRequest request)
        {
            return base.Channel.getDataPasienByID(request);
        }
        
        public bool getDataPasienByID(ref Tracking_Vaksin_Services.DataPasienS dataPasienS, int ID, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.getDataPasienByIDRequest inValue = new ServiceModelDataPasien.getDataPasienByIDRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.ID = ID;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.getDataPasienByIDResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).getDataPasienByID(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getDataPasienByIDResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByIDResponse> getDataPasienByIDAsync(ServiceModelDataPasien.getDataPasienByIDRequest request)
        {
            return base.Channel.getDataPasienByIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.getDataPasienByIDPendudukResponse ServiceModelDataPasien.IServiceModelDataPasien.getDataPasienByIDPenduduk(ServiceModelDataPasien.getDataPasienByIDPendudukRequest request)
        {
            return base.Channel.getDataPasienByIDPenduduk(request);
        }
        
        public bool getDataPasienByIDPenduduk(ref Tracking_Vaksin_Services.DataPasienS dataPasienS, int IDPenduduk, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.getDataPasienByIDPendudukRequest inValue = new ServiceModelDataPasien.getDataPasienByIDPendudukRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.IDPenduduk = IDPenduduk;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.getDataPasienByIDPendudukResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).getDataPasienByIDPenduduk(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getDataPasienByIDPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByIDPendudukResponse> getDataPasienByIDPendudukAsync(ServiceModelDataPasien.getDataPasienByIDPendudukRequest request)
        {
            return base.Channel.getDataPasienByIDPendudukAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.getDataPasienByNIKResponse ServiceModelDataPasien.IServiceModelDataPasien.getDataPasienByNIK(ServiceModelDataPasien.getDataPasienByNIKRequest request)
        {
            return base.Channel.getDataPasienByNIK(request);
        }
        
        public bool getDataPasienByNIK(ref Tracking_Vaksin_Services.DataPasienS dataPasienS, string NIK, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.getDataPasienByNIKRequest inValue = new ServiceModelDataPasien.getDataPasienByNIKRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.NIK = NIK;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.getDataPasienByNIKResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).getDataPasienByNIK(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getDataPasienByNIKResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.getDataPasienByNIKResponse> getDataPasienByNIKAsync(ServiceModelDataPasien.getDataPasienByNIKRequest request)
        {
            return base.Channel.getDataPasienByNIKAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.createDataPasienResponse ServiceModelDataPasien.IServiceModelDataPasien.createDataPasien(ServiceModelDataPasien.createDataPasienRequest request)
        {
            return base.Channel.createDataPasien(request);
        }
        
        public bool createDataPasien(ref Tracking_Vaksin_Services.DataPasienS dataPasienS, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.createDataPasienRequest inValue = new ServiceModelDataPasien.createDataPasienRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.createDataPasienResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).createDataPasien(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.createDataPasienResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.createDataPasienResponse> createDataPasienAsync(ServiceModelDataPasien.createDataPasienRequest request)
        {
            return base.Channel.createDataPasienAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.updateDataPasienResponse ServiceModelDataPasien.IServiceModelDataPasien.updateDataPasien(ServiceModelDataPasien.updateDataPasienRequest request)
        {
            return base.Channel.updateDataPasien(request);
        }
        
        public bool updateDataPasien(ref Tracking_Vaksin_Services.DataPasienS dataPasienS, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.updateDataPasienRequest inValue = new ServiceModelDataPasien.updateDataPasienRequest();
            inValue.dataPasienS = dataPasienS;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.updateDataPasienResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).updateDataPasien(inValue);
            dataPasienS = retVal.dataPasienS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.updateDataPasienResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.updateDataPasienResponse> updateDataPasienAsync(ServiceModelDataPasien.updateDataPasienRequest request)
        {
            return base.Channel.updateDataPasienAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPasien.deleteDataPasienResponse ServiceModelDataPasien.IServiceModelDataPasien.deleteDataPasien(ServiceModelDataPasien.deleteDataPasienRequest request)
        {
            return base.Channel.deleteDataPasien(request);
        }
        
        public bool deleteDataPasien(int id, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPasien.deleteDataPasienRequest inValue = new ServiceModelDataPasien.deleteDataPasienRequest();
            inValue.id = id;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPasien.deleteDataPasienResponse retVal = ((ServiceModelDataPasien.IServiceModelDataPasien)(this)).deleteDataPasien(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.deleteDataPasienResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPasien.deleteDataPasienResponse> deleteDataPasienAsync(ServiceModelDataPasien.deleteDataPasienRequest request)
        {
            return base.Channel.deleteDataPasienAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelDataPasien))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelDataPasien))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServiceModelDataPasien.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceModelDataPasienClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceModelDataPasien);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceModelDataPasienClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceModelDataPasien);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceModelDataPasien,
        }
    }
}
