//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicePemerintah
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePemerintah.IServicePemerintah")]
    public interface IServicePemerintah
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePemerintah/KonfirmasiNIKPenduduk", ReplyAction="http://tempuri.org/IServicePemerintah/KonfirmasiNIKPendudukResponse")]
        ServicePemerintah.KonfirmasiNIKPendudukResponse KonfirmasiNIKPenduduk(ServicePemerintah.KonfirmasiNIKPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePemerintah/KonfirmasiNIKPenduduk", ReplyAction="http://tempuri.org/IServicePemerintah/KonfirmasiNIKPendudukResponse")]
        System.Threading.Tasks.Task<ServicePemerintah.KonfirmasiNIKPendudukResponse> KonfirmasiNIKPendudukAsync(ServicePemerintah.KonfirmasiNIKPendudukRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KonfirmasiNIKPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KonfirmasiNIKPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NIK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public KonfirmasiNIKPendudukRequest()
        {
        }
        
        public KonfirmasiNIKPendudukRequest(string NIK, int StatusCode, string Message)
        {
            this.NIK = NIK;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KonfirmasiNIKPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KonfirmasiNIKPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool KonfirmasiNIKPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public KonfirmasiNIKPendudukResponse()
        {
        }
        
        public KonfirmasiNIKPendudukResponse(bool KonfirmasiNIKPendudukResult, int StatusCode, string Message)
        {
            this.KonfirmasiNIKPendudukResult = KonfirmasiNIKPendudukResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicePemerintahChannel : ServicePemerintah.IServicePemerintah, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicePemerintahClient : System.ServiceModel.ClientBase<ServicePemerintah.IServicePemerintah>, ServicePemerintah.IServicePemerintah
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicePemerintahClient() : 
                base(ServicePemerintahClient.GetDefaultBinding(), ServicePemerintahClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicePemerintah.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePemerintahClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicePemerintahClient.GetBindingForEndpoint(endpointConfiguration), ServicePemerintahClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePemerintahClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicePemerintahClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePemerintahClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicePemerintahClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePemerintahClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServicePemerintah.KonfirmasiNIKPendudukResponse ServicePemerintah.IServicePemerintah.KonfirmasiNIKPenduduk(ServicePemerintah.KonfirmasiNIKPendudukRequest request)
        {
            return base.Channel.KonfirmasiNIKPenduduk(request);
        }
        
        public bool KonfirmasiNIKPenduduk(string NIK, ref int StatusCode, ref string Message)
        {
            ServicePemerintah.KonfirmasiNIKPendudukRequest inValue = new ServicePemerintah.KonfirmasiNIKPendudukRequest();
            inValue.NIK = NIK;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServicePemerintah.KonfirmasiNIKPendudukResponse retVal = ((ServicePemerintah.IServicePemerintah)(this)).KonfirmasiNIKPenduduk(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.KonfirmasiNIKPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServicePemerintah.KonfirmasiNIKPendudukResponse> KonfirmasiNIKPendudukAsync(ServicePemerintah.KonfirmasiNIKPendudukRequest request)
        {
            return base.Channel.KonfirmasiNIKPendudukAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicePemerintah))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicePemerintah))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServicePemerintah.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicePemerintahClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicePemerintah);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicePemerintahClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicePemerintah);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicePemerintah,
        }
    }
}
