//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceModelDataPenduduk
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPendudukS", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class DataPendudukS : object
    {
        
        private string alamatField;
        
        private int idField;
        
        private System.Nullable<int> id_pemerintahField;
        
        private string jenis_kelaminField;
        
        private string namaField;
        
        private string nikField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat
        {
            get
            {
                return this.alamatField;
            }
            set
            {
                this.alamatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_pemerintah
        {
            get
            {
                return this.id_pemerintahField;
            }
            set
            {
                this.id_pemerintahField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin
        {
            get
            {
                return this.jenis_kelaminField;
            }
            set
            {
                this.jenis_kelaminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nik
        {
            get
            {
                return this.nikField;
            }
            set
            {
                this.nikField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceModelDataPenduduk.IServiceModelDataPenduduk")]
    public interface IServiceModelDataPenduduk
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getAllDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getAllDataPendudukResponse")]
        ServiceModelDataPenduduk.getAllDataPendudukResponse getAllDataPenduduk(ServiceModelDataPenduduk.getAllDataPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getAllDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getAllDataPendudukResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.getAllDataPendudukResponse> getAllDataPendudukAsync(ServiceModelDataPenduduk.getAllDataPendudukRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByID", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByIDResponse")]
        ServiceModelDataPenduduk.getDataPendudukByIDResponse getDataPendudukByID(ServiceModelDataPenduduk.getDataPendudukByIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByID", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByIDResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.getDataPendudukByIDResponse> getDataPendudukByIDAsync(ServiceModelDataPenduduk.getDataPendudukByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByNIK", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByNIKResponse")]
        ServiceModelDataPenduduk.getDataPendudukByNIKResponse getDataPendudukByNIK(ServiceModelDataPenduduk.getDataPendudukByNIKRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByNIK", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/getDataPendudukByNIKResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.getDataPendudukByNIKResponse> getDataPendudukByNIKAsync(ServiceModelDataPenduduk.getDataPendudukByNIKRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/createDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/createDataPendudukResponse")]
        ServiceModelDataPenduduk.createDataPendudukResponse createDataPenduduk(ServiceModelDataPenduduk.createDataPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/createDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/createDataPendudukResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.createDataPendudukResponse> createDataPendudukAsync(ServiceModelDataPenduduk.createDataPendudukRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/updateDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/updateDataPendudukResponse")]
        ServiceModelDataPenduduk.updateDataPendudukResponse updateDataPenduduk(ServiceModelDataPenduduk.updateDataPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/updateDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/updateDataPendudukResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.updateDataPendudukResponse> updateDataPendudukAsync(ServiceModelDataPenduduk.updateDataPendudukRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/deleteDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/deleteDataPendudukResponse")]
        ServiceModelDataPenduduk.deleteDataPendudukResponse deleteDataPenduduk(ServiceModelDataPenduduk.deleteDataPendudukRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelDataPenduduk/deleteDataPenduduk", ReplyAction="http://tempuri.org/IServiceModelDataPenduduk/deleteDataPendudukResponse")]
        System.Threading.Tasks.Task<ServiceModelDataPenduduk.deleteDataPendudukResponse> deleteDataPendudukAsync(ServiceModelDataPenduduk.deleteDataPendudukRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllDataPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceModelDataPenduduk.DataPendudukS> dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public getAllDataPendudukRequest()
        {
        }
        
        public getAllDataPendudukRequest(System.Collections.Generic.List<ServiceModelDataPenduduk.DataPendudukS> dataPenduduk, int StatusCode, string Message)
        {
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getAllDataPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getAllDataPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<ServiceModelDataPenduduk.DataPendudukS> dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getAllDataPendudukResponse()
        {
        }
        
        public getAllDataPendudukResponse(bool getAllDataPendudukResult, System.Collections.Generic.List<ServiceModelDataPenduduk.DataPendudukS> dataPenduduk, int StatusCode, string Message)
        {
            this.getAllDataPendudukResult = getAllDataPendudukResult;
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPendudukByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPendudukByIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPendudukByIDRequest()
        {
        }
        
        public getDataPendudukByIDRequest(ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int ID, int StatusCode, string Message)
        {
            this.dataPenduduk = dataPenduduk;
            this.ID = ID;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPendudukByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPendudukByIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getDataPendudukByIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPendudukByIDResponse()
        {
        }
        
        public getDataPendudukByIDResponse(bool getDataPendudukByIDResult, ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.getDataPendudukByIDResult = getDataPendudukByIDResult;
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPendudukByNIK", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPendudukByNIKRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NIK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPendudukByNIKRequest()
        {
        }
        
        public getDataPendudukByNIKRequest(ServiceModelDataPenduduk.DataPendudukS dataPenduduk, string NIK, int StatusCode, string Message)
        {
            this.dataPenduduk = dataPenduduk;
            this.NIK = NIK;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataPendudukByNIKResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getDataPendudukByNIKResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getDataPendudukByNIKResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getDataPendudukByNIKResponse()
        {
        }
        
        public getDataPendudukByNIKResponse(bool getDataPendudukByNIKResult, ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.getDataPendudukByNIKResult = getDataPendudukByNIKResult;
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDataPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDataPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public createDataPendudukRequest()
        {
        }
        
        public createDataPendudukRequest(ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDataPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class createDataPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool createDataPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public createDataPendudukResponse()
        {
        }
        
        public createDataPendudukResponse(bool createDataPendudukResult, ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.createDataPendudukResult = createDataPendudukResult;
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDataPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateDataPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public updateDataPendudukRequest()
        {
        }
        
        public updateDataPendudukRequest(ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDataPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class updateDataPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool updateDataPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelDataPenduduk.DataPendudukS dataPenduduk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public updateDataPendudukResponse()
        {
        }
        
        public updateDataPendudukResponse(bool updateDataPendudukResult, ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int StatusCode, string Message)
        {
            this.updateDataPendudukResult = updateDataPendudukResult;
            this.dataPenduduk = dataPenduduk;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDataPenduduk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteDataPendudukRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public deleteDataPendudukRequest()
        {
        }
        
        public deleteDataPendudukRequest(int id, int StatusCode, string Message)
        {
            this.id = id;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteDataPendudukResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteDataPendudukResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool deleteDataPendudukResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public deleteDataPendudukResponse()
        {
        }
        
        public deleteDataPendudukResponse(bool deleteDataPendudukResult, int StatusCode, string Message)
        {
            this.deleteDataPendudukResult = deleteDataPendudukResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceModelDataPendudukChannel : ServiceModelDataPenduduk.IServiceModelDataPenduduk, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceModelDataPendudukClient : System.ServiceModel.ClientBase<ServiceModelDataPenduduk.IServiceModelDataPenduduk>, ServiceModelDataPenduduk.IServiceModelDataPenduduk
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceModelDataPendudukClient() : 
                base(ServiceModelDataPendudukClient.GetDefaultBinding(), ServiceModelDataPendudukClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceModelDataPenduduk.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPendudukClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceModelDataPendudukClient.GetBindingForEndpoint(endpointConfiguration), ServiceModelDataPendudukClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPendudukClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceModelDataPendudukClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPendudukClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceModelDataPendudukClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelDataPendudukClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.getAllDataPendudukResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.getAllDataPenduduk(ServiceModelDataPenduduk.getAllDataPendudukRequest request)
        {
            return base.Channel.getAllDataPenduduk(request);
        }
        
        public bool getAllDataPenduduk(ref System.Collections.Generic.List<ServiceModelDataPenduduk.DataPendudukS> dataPenduduk, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.getAllDataPendudukRequest inValue = new ServiceModelDataPenduduk.getAllDataPendudukRequest();
            inValue.dataPenduduk = dataPenduduk;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.getAllDataPendudukResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).getAllDataPenduduk(inValue);
            dataPenduduk = retVal.dataPenduduk;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getAllDataPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.getAllDataPendudukResponse> getAllDataPendudukAsync(ServiceModelDataPenduduk.getAllDataPendudukRequest request)
        {
            return base.Channel.getAllDataPendudukAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.getDataPendudukByIDResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.getDataPendudukByID(ServiceModelDataPenduduk.getDataPendudukByIDRequest request)
        {
            return base.Channel.getDataPendudukByID(request);
        }
        
        public bool getDataPendudukByID(ref ServiceModelDataPenduduk.DataPendudukS dataPenduduk, int ID, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.getDataPendudukByIDRequest inValue = new ServiceModelDataPenduduk.getDataPendudukByIDRequest();
            inValue.dataPenduduk = dataPenduduk;
            inValue.ID = ID;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.getDataPendudukByIDResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).getDataPendudukByID(inValue);
            dataPenduduk = retVal.dataPenduduk;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getDataPendudukByIDResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.getDataPendudukByIDResponse> getDataPendudukByIDAsync(ServiceModelDataPenduduk.getDataPendudukByIDRequest request)
        {
            return base.Channel.getDataPendudukByIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.getDataPendudukByNIKResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.getDataPendudukByNIK(ServiceModelDataPenduduk.getDataPendudukByNIKRequest request)
        {
            return base.Channel.getDataPendudukByNIK(request);
        }
        
        public bool getDataPendudukByNIK(ref ServiceModelDataPenduduk.DataPendudukS dataPenduduk, string NIK, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.getDataPendudukByNIKRequest inValue = new ServiceModelDataPenduduk.getDataPendudukByNIKRequest();
            inValue.dataPenduduk = dataPenduduk;
            inValue.NIK = NIK;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.getDataPendudukByNIKResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).getDataPendudukByNIK(inValue);
            dataPenduduk = retVal.dataPenduduk;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getDataPendudukByNIKResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.getDataPendudukByNIKResponse> getDataPendudukByNIKAsync(ServiceModelDataPenduduk.getDataPendudukByNIKRequest request)
        {
            return base.Channel.getDataPendudukByNIKAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.createDataPendudukResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.createDataPenduduk(ServiceModelDataPenduduk.createDataPendudukRequest request)
        {
            return base.Channel.createDataPenduduk(request);
        }
        
        public bool createDataPenduduk(ref ServiceModelDataPenduduk.DataPendudukS dataPenduduk, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.createDataPendudukRequest inValue = new ServiceModelDataPenduduk.createDataPendudukRequest();
            inValue.dataPenduduk = dataPenduduk;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.createDataPendudukResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).createDataPenduduk(inValue);
            dataPenduduk = retVal.dataPenduduk;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.createDataPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.createDataPendudukResponse> createDataPendudukAsync(ServiceModelDataPenduduk.createDataPendudukRequest request)
        {
            return base.Channel.createDataPendudukAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.updateDataPendudukResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.updateDataPenduduk(ServiceModelDataPenduduk.updateDataPendudukRequest request)
        {
            return base.Channel.updateDataPenduduk(request);
        }
        
        public bool updateDataPenduduk(ref ServiceModelDataPenduduk.DataPendudukS dataPenduduk, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.updateDataPendudukRequest inValue = new ServiceModelDataPenduduk.updateDataPendudukRequest();
            inValue.dataPenduduk = dataPenduduk;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.updateDataPendudukResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).updateDataPenduduk(inValue);
            dataPenduduk = retVal.dataPenduduk;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.updateDataPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.updateDataPendudukResponse> updateDataPendudukAsync(ServiceModelDataPenduduk.updateDataPendudukRequest request)
        {
            return base.Channel.updateDataPendudukAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelDataPenduduk.deleteDataPendudukResponse ServiceModelDataPenduduk.IServiceModelDataPenduduk.deleteDataPenduduk(ServiceModelDataPenduduk.deleteDataPendudukRequest request)
        {
            return base.Channel.deleteDataPenduduk(request);
        }
        
        public bool deleteDataPenduduk(int id, ref int StatusCode, ref string Message)
        {
            ServiceModelDataPenduduk.deleteDataPendudukRequest inValue = new ServiceModelDataPenduduk.deleteDataPendudukRequest();
            inValue.id = id;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelDataPenduduk.deleteDataPendudukResponse retVal = ((ServiceModelDataPenduduk.IServiceModelDataPenduduk)(this)).deleteDataPenduduk(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.deleteDataPendudukResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelDataPenduduk.deleteDataPendudukResponse> deleteDataPendudukAsync(ServiceModelDataPenduduk.deleteDataPendudukRequest request)
        {
            return base.Channel.deleteDataPendudukAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelDataPenduduk))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelDataPenduduk))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServiceModelDataPenduduk.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceModelDataPendudukClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceModelDataPenduduk);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceModelDataPendudukClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceModelDataPenduduk);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceModelDataPenduduk,
        }
    }
}
