//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDataModelMasyarakat
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDataModelMasyarakat.IServiceModelMasyarakat")]
    public interface IServiceModelMasyarakat
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelMasyarakat/register", ReplyAction="http://tempuri.org/IServiceModelMasyarakat/registerResponse")]
        ServiceDataModelMasyarakat.registerResponse register(ServiceDataModelMasyarakat.registerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelMasyarakat/register", ReplyAction="http://tempuri.org/IServiceModelMasyarakat/registerResponse")]
        System.Threading.Tasks.Task<ServiceDataModelMasyarakat.registerResponse> registerAsync(ServiceDataModelMasyarakat.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelMasyarakat/login", ReplyAction="http://tempuri.org/IServiceModelMasyarakat/loginResponse")]
        ServiceDataModelMasyarakat.loginResponse login(ServiceDataModelMasyarakat.loginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelMasyarakat/login", ReplyAction="http://tempuri.org/IServiceModelMasyarakat/loginResponse")]
        System.Threading.Tasks.Task<ServiceDataModelMasyarakat.loginResponse> loginAsync(ServiceDataModelMasyarakat.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nik;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Message;
        
        public registerRequest()
        {
        }
        
        public registerRequest(string username, string password, string nik, int StatusCode, string Message)
        {
            this.username = username;
            this.password = password;
            this.nik = nik;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool registerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public registerResponse()
        {
        }
        
        public registerResponse(bool registerResult, int StatusCode, string Message)
        {
            this.registerResult = registerResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Tracking_Vaksin_Services.MasyarakatS masyarakatS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.DataPendudukS dataPendudukS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Message;
        
        public loginRequest()
        {
        }
        
        public loginRequest(Tracking_Vaksin_Services.MasyarakatS masyarakatS, Tracking_Vaksin_Services.DataPendudukS dataPendudukS, string username, string password, int StatusCode, string Message)
        {
            this.masyarakatS = masyarakatS;
            this.dataPendudukS = dataPendudukS;
            this.username = username;
            this.password = password;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool loginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Tracking_Vaksin_Services.MasyarakatS masyarakatS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public Tracking_Vaksin_Services.DataPendudukS dataPendudukS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Message;
        
        public loginResponse()
        {
        }
        
        public loginResponse(bool loginResult, Tracking_Vaksin_Services.MasyarakatS masyarakatS, Tracking_Vaksin_Services.DataPendudukS dataPendudukS, int StatusCode, string Message)
        {
            this.loginResult = loginResult;
            this.masyarakatS = masyarakatS;
            this.dataPendudukS = dataPendudukS;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceModelMasyarakatChannel : ServiceDataModelMasyarakat.IServiceModelMasyarakat, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceModelMasyarakatClient : System.ServiceModel.ClientBase<ServiceDataModelMasyarakat.IServiceModelMasyarakat>, ServiceDataModelMasyarakat.IServiceModelMasyarakat
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceModelMasyarakatClient() : 
                base(ServiceModelMasyarakatClient.GetDefaultBinding(), ServiceModelMasyarakatClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceModelMasyarakat.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelMasyarakatClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceModelMasyarakatClient.GetBindingForEndpoint(endpointConfiguration), ServiceModelMasyarakatClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelMasyarakatClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceModelMasyarakatClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelMasyarakatClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceModelMasyarakatClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelMasyarakatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDataModelMasyarakat.registerResponse ServiceDataModelMasyarakat.IServiceModelMasyarakat.register(ServiceDataModelMasyarakat.registerRequest request)
        {
            return base.Channel.register(request);
        }
        
        public bool register(string username, string password, string nik, ref int StatusCode, ref string Message)
        {
            ServiceDataModelMasyarakat.registerRequest inValue = new ServiceDataModelMasyarakat.registerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.nik = nik;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceDataModelMasyarakat.registerResponse retVal = ((ServiceDataModelMasyarakat.IServiceModelMasyarakat)(this)).register(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.registerResult;
        }
        
        public System.Threading.Tasks.Task<ServiceDataModelMasyarakat.registerResponse> registerAsync(ServiceDataModelMasyarakat.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDataModelMasyarakat.loginResponse ServiceDataModelMasyarakat.IServiceModelMasyarakat.login(ServiceDataModelMasyarakat.loginRequest request)
        {
            return base.Channel.login(request);
        }
        
        public bool login(ref Tracking_Vaksin_Services.MasyarakatS masyarakatS, ref Tracking_Vaksin_Services.DataPendudukS dataPendudukS, string username, string password, ref int StatusCode, ref string Message)
        {
            ServiceDataModelMasyarakat.loginRequest inValue = new ServiceDataModelMasyarakat.loginRequest();
            inValue.masyarakatS = masyarakatS;
            inValue.dataPendudukS = dataPendudukS;
            inValue.username = username;
            inValue.password = password;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceDataModelMasyarakat.loginResponse retVal = ((ServiceDataModelMasyarakat.IServiceModelMasyarakat)(this)).login(inValue);
            masyarakatS = retVal.masyarakatS;
            dataPendudukS = retVal.dataPendudukS;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.loginResult;
        }
        
        public System.Threading.Tasks.Task<ServiceDataModelMasyarakat.loginResponse> loginAsync(ServiceDataModelMasyarakat.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelMasyarakat))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelMasyarakat))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServiceModelMasyarakat.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceModelMasyarakatClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceModelMasyarakat);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceModelMasyarakatClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceModelMasyarakat);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceModelMasyarakat,
        }
    }
}
