//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceModelProdusen
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdusenS", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class ProdusenS : object
    {
        
        private int idField;
        
        private string namaField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceModelProdusen.IServiceModelProdusen")]
    public interface IServiceModelProdusen
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/register", ReplyAction="http://tempuri.org/IServiceModelProdusen/registerResponse")]
        ServiceModelProdusen.registerResponse register(ServiceModelProdusen.registerRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/register", ReplyAction="http://tempuri.org/IServiceModelProdusen/registerResponse")]
        System.Threading.Tasks.Task<ServiceModelProdusen.registerResponse> registerAsync(ServiceModelProdusen.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/login", ReplyAction="http://tempuri.org/IServiceModelProdusen/loginResponse")]
        ServiceModelProdusen.loginResponse login(ServiceModelProdusen.loginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/login", ReplyAction="http://tempuri.org/IServiceModelProdusen/loginResponse")]
        System.Threading.Tasks.Task<ServiceModelProdusen.loginResponse> loginAsync(ServiceModelProdusen.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/getProdusenById", ReplyAction="http://tempuri.org/IServiceModelProdusen/getProdusenByIdResponse")]
        ServiceModelProdusen.getProdusenByIdResponse getProdusenById(ServiceModelProdusen.getProdusenByIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModelProdusen/getProdusenById", ReplyAction="http://tempuri.org/IServiceModelProdusen/getProdusenByIdResponse")]
        System.Threading.Tasks.Task<ServiceModelProdusen.getProdusenByIdResponse> getProdusenByIdAsync(ServiceModelProdusen.getProdusenByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class registerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string nama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Message;
        
        public registerRequest()
        {
        }
        
        public registerRequest(string username, string password, string nama, int StatusCode, string Message)
        {
            this.username = username;
            this.password = password;
            this.nama = nama;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class registerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool registerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public registerResponse()
        {
        }
        
        public registerResponse(bool registerResult, int StatusCode, string Message)
        {
            this.registerResult = registerResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelProdusen.ProdusenS produsen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Message;
        
        public loginRequest()
        {
        }
        
        public loginRequest(ServiceModelProdusen.ProdusenS produsen, string username, string password, int StatusCode, string Message)
        {
            this.produsen = produsen;
            this.username = username;
            this.password = password;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool loginResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelProdusen.ProdusenS produsen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public loginResponse()
        {
        }
        
        public loginResponse(bool loginResult, ServiceModelProdusen.ProdusenS produsen, int StatusCode, string Message)
        {
            this.loginResult = loginResult;
            this.produsen = produsen;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProdusenById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getProdusenByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceModelProdusen.ProdusenS produsen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getProdusenByIdRequest()
        {
        }
        
        public getProdusenByIdRequest(ServiceModelProdusen.ProdusenS produsen, int id, int StatusCode, string Message)
        {
            this.produsen = produsen;
            this.id = id;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProdusenByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getProdusenByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool getProdusenByIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ServiceModelProdusen.ProdusenS produsen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Message;
        
        public getProdusenByIdResponse()
        {
        }
        
        public getProdusenByIdResponse(bool getProdusenByIdResult, ServiceModelProdusen.ProdusenS produsen, int StatusCode, string Message)
        {
            this.getProdusenByIdResult = getProdusenByIdResult;
            this.produsen = produsen;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceModelProdusenChannel : ServiceModelProdusen.IServiceModelProdusen, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceModelProdusenClient : System.ServiceModel.ClientBase<ServiceModelProdusen.IServiceModelProdusen>, ServiceModelProdusen.IServiceModelProdusen
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceModelProdusenClient() : 
                base(ServiceModelProdusenClient.GetDefaultBinding(), ServiceModelProdusenClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceModelProdusen.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelProdusenClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceModelProdusenClient.GetBindingForEndpoint(endpointConfiguration), ServiceModelProdusenClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelProdusenClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceModelProdusenClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelProdusenClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceModelProdusenClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceModelProdusenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelProdusen.registerResponse ServiceModelProdusen.IServiceModelProdusen.register(ServiceModelProdusen.registerRequest request)
        {
            return base.Channel.register(request);
        }
        
        public bool register(string username, string password, string nama, ref int StatusCode, ref string Message)
        {
            ServiceModelProdusen.registerRequest inValue = new ServiceModelProdusen.registerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.nama = nama;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelProdusen.registerResponse retVal = ((ServiceModelProdusen.IServiceModelProdusen)(this)).register(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.registerResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelProdusen.registerResponse> registerAsync(ServiceModelProdusen.registerRequest request)
        {
            return base.Channel.registerAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelProdusen.loginResponse ServiceModelProdusen.IServiceModelProdusen.login(ServiceModelProdusen.loginRequest request)
        {
            return base.Channel.login(request);
        }
        
        public bool login(ref ServiceModelProdusen.ProdusenS produsen, string username, string password, ref int StatusCode, ref string Message)
        {
            ServiceModelProdusen.loginRequest inValue = new ServiceModelProdusen.loginRequest();
            inValue.produsen = produsen;
            inValue.username = username;
            inValue.password = password;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelProdusen.loginResponse retVal = ((ServiceModelProdusen.IServiceModelProdusen)(this)).login(inValue);
            produsen = retVal.produsen;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.loginResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelProdusen.loginResponse> loginAsync(ServiceModelProdusen.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceModelProdusen.getProdusenByIdResponse ServiceModelProdusen.IServiceModelProdusen.getProdusenById(ServiceModelProdusen.getProdusenByIdRequest request)
        {
            return base.Channel.getProdusenById(request);
        }
        
        public bool getProdusenById(ref ServiceModelProdusen.ProdusenS produsen, int id, ref int StatusCode, ref string Message)
        {
            ServiceModelProdusen.getProdusenByIdRequest inValue = new ServiceModelProdusen.getProdusenByIdRequest();
            inValue.produsen = produsen;
            inValue.id = id;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceModelProdusen.getProdusenByIdResponse retVal = ((ServiceModelProdusen.IServiceModelProdusen)(this)).getProdusenById(inValue);
            produsen = retVal.produsen;
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.getProdusenByIdResult;
        }
        
        public System.Threading.Tasks.Task<ServiceModelProdusen.getProdusenByIdResponse> getProdusenByIdAsync(ServiceModelProdusen.getProdusenByIdRequest request)
        {
            return base.Channel.getProdusenByIdAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelProdusen))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceModelProdusen))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServiceModelProdusen.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceModelProdusenClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceModelProdusen);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceModelProdusenClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceModelProdusen);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceModelProdusen,
        }
    }
}
