//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBPOM
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVaksin", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class DataVaksin : object
    {
        
        private System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasienField;
        
        private ServiceBPOM.Produsen ProdusenField;
        
        private ServiceBPOM.RumahSakit RumahSakitField;
        
        private int idField;
        
        private System.Nullable<int> id_produsenField;
        
        private System.Nullable<int> id_rumahsakit_penerimaField;
        
        private System.Nullable<int> jumlahField;
        
        private System.Nullable<int> jumlah_pakaiField;
        
        private string namaField;
        
        private string no_registrasiField;
        
        private System.Nullable<System.DateTime> tgl_pembuatanField;
        
        private System.Nullable<System.DateTime> tgl_terimaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasien
        {
            get
            {
                return this.DataPasienField;
            }
            set
            {
                this.DataPasienField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.Produsen Produsen
        {
            get
            {
                return this.ProdusenField;
            }
            set
            {
                this.ProdusenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.RumahSakit RumahSakit
        {
            get
            {
                return this.RumahSakitField;
            }
            set
            {
                this.RumahSakitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_produsen
        {
            get
            {
                return this.id_produsenField;
            }
            set
            {
                this.id_produsenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_rumahsakit_penerima
        {
            get
            {
                return this.id_rumahsakit_penerimaField;
            }
            set
            {
                this.id_rumahsakit_penerimaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> jumlah
        {
            get
            {
                return this.jumlahField;
            }
            set
            {
                this.jumlahField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> jumlah_pakai
        {
            get
            {
                return this.jumlah_pakaiField;
            }
            set
            {
                this.jumlah_pakaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string no_registrasi
        {
            get
            {
                return this.no_registrasiField;
            }
            set
            {
                this.no_registrasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> tgl_pembuatan
        {
            get
            {
                return this.tgl_pembuatanField;
            }
            set
            {
                this.tgl_pembuatanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> tgl_terima
        {
            get
            {
                return this.tgl_terimaField;
            }
            set
            {
                this.tgl_terimaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produsen", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class Produsen : object
    {
        
        private System.Collections.Generic.List<ServiceBPOM.DataVaksin> DataVaksinField;
        
        private int idField;
        
        private string namaField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataVaksin> DataVaksin
        {
            get
            {
                return this.DataVaksinField;
            }
            set
            {
                this.DataVaksinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RumahSakit", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class RumahSakit : object
    {
        
        private System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasienField;
        
        private System.Collections.Generic.List<ServiceBPOM.DataVaksin> DataVaksinField;
        
        private string alamatField;
        
        private int idField;
        
        private string namaField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasien
        {
            get
            {
                return this.DataPasienField;
            }
            set
            {
                this.DataPasienField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataVaksin> DataVaksin
        {
            get
            {
                return this.DataVaksinField;
            }
            set
            {
                this.DataVaksinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat
        {
            get
            {
                return this.alamatField;
            }
            set
            {
                this.alamatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPasien", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class DataPasien : object
    {
        
        private ServiceBPOM.DataPenduduk DataPendudukField;
        
        private ServiceBPOM.DataVaksin DataVaksinField;
        
        private ServiceBPOM.RumahSakit RumahSakitField;
        
        private int idField;
        
        private System.Nullable<int> id_pendudukField;
        
        private System.Nullable<int> id_rumahsakitField;
        
        private System.Nullable<int> id_vaksinField;
        
        private string nikField;
        
        private System.Nullable<System.DateTime> tgl_terimavaksinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.DataPenduduk DataPenduduk
        {
            get
            {
                return this.DataPendudukField;
            }
            set
            {
                this.DataPendudukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.DataVaksin DataVaksin
        {
            get
            {
                return this.DataVaksinField;
            }
            set
            {
                this.DataVaksinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.RumahSakit RumahSakit
        {
            get
            {
                return this.RumahSakitField;
            }
            set
            {
                this.RumahSakitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_penduduk
        {
            get
            {
                return this.id_pendudukField;
            }
            set
            {
                this.id_pendudukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_rumahsakit
        {
            get
            {
                return this.id_rumahsakitField;
            }
            set
            {
                this.id_rumahsakitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_vaksin
        {
            get
            {
                return this.id_vaksinField;
            }
            set
            {
                this.id_vaksinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nik
        {
            get
            {
                return this.nikField;
            }
            set
            {
                this.nikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> tgl_terimavaksin
        {
            get
            {
                return this.tgl_terimavaksinField;
            }
            set
            {
                this.tgl_terimavaksinField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPenduduk", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class DataPenduduk : object
    {
        
        private System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasienField;
        
        private System.Collections.Generic.List<ServiceBPOM.Masyarakat> MasyarakatField;
        
        private ServiceBPOM.Pemerintah PemerintahField;
        
        private string alamatField;
        
        private int idField;
        
        private System.Nullable<int> id_pemerintahField;
        
        private string jenis_kelaminField;
        
        private string namaField;
        
        private string nikField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataPasien> DataPasien
        {
            get
            {
                return this.DataPasienField;
            }
            set
            {
                this.DataPasienField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.Masyarakat> Masyarakat
        {
            get
            {
                return this.MasyarakatField;
            }
            set
            {
                this.MasyarakatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.Pemerintah Pemerintah
        {
            get
            {
                return this.PemerintahField;
            }
            set
            {
                this.PemerintahField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alamat
        {
            get
            {
                return this.alamatField;
            }
            set
            {
                this.alamatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_pemerintah
        {
            get
            {
                return this.id_pemerintahField;
            }
            set
            {
                this.id_pemerintahField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jenis_kelamin
        {
            get
            {
                return this.jenis_kelaminField;
            }
            set
            {
                this.jenis_kelaminField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama
        {
            get
            {
                return this.namaField;
            }
            set
            {
                this.namaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nik
        {
            get
            {
                return this.nikField;
            }
            set
            {
                this.nikField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pemerintah", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class Pemerintah : object
    {
        
        private System.Collections.Generic.List<ServiceBPOM.DataPenduduk> DataPendudukField;
        
        private int idField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceBPOM.DataPenduduk> DataPenduduk
        {
            get
            {
                return this.DataPendudukField;
            }
            set
            {
                this.DataPendudukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Masyarakat", Namespace="http://schemas.datacontract.org/2004/07/Tracking_Vaksin_Services")]
    public partial class Masyarakat : object
    {
        
        private ServiceBPOM.DataPenduduk DataPendudukField;
        
        private int idField;
        
        private System.Nullable<int> id_data_pendudukField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBPOM.DataPenduduk DataPenduduk
        {
            get
            {
                return this.DataPendudukField;
            }
            set
            {
                this.DataPendudukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> id_data_penduduk
        {
            get
            {
                return this.id_data_pendudukField;
            }
            set
            {
                this.id_data_pendudukField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBPOM.IServiceBPOM")]
    public interface IServiceBPOM
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/RegistrasiVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/RegistrasiVaksinResponse")]
        ServiceBPOM.RegistrasiVaksinResponse RegistrasiVaksin(ServiceBPOM.RegistrasiVaksinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/RegistrasiVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/RegistrasiVaksinResponse")]
        System.Threading.Tasks.Task<ServiceBPOM.RegistrasiVaksinResponse> RegistrasiVaksinAsync(ServiceBPOM.RegistrasiVaksinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/LaporKedatanganVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/LaporKedatanganVaksinResponse")]
        ServiceBPOM.LaporKedatanganVaksinResponse LaporKedatanganVaksin(ServiceBPOM.LaporKedatanganVaksinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/LaporKedatanganVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/LaporKedatanganVaksinResponse")]
        System.Threading.Tasks.Task<ServiceBPOM.LaporKedatanganVaksinResponse> LaporKedatanganVaksinAsync(ServiceBPOM.LaporKedatanganVaksinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/LaporPenggunaanVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/LaporPenggunaanVaksinResponse")]
        ServiceBPOM.LaporPenggunaanVaksinResponse LaporPenggunaanVaksin(ServiceBPOM.LaporPenggunaanVaksinRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBPOM/LaporPenggunaanVaksin", ReplyAction="http://tempuri.org/IServiceBPOM/LaporPenggunaanVaksinResponse")]
        System.Threading.Tasks.Task<ServiceBPOM.LaporPenggunaanVaksinResponse> LaporPenggunaanVaksinAsync(ServiceBPOM.LaporPenggunaanVaksinRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrasiVaksin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrasiVaksinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceBPOM.DataVaksin Vaksin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public RegistrasiVaksinRequest()
        {
        }
        
        public RegistrasiVaksinRequest(ServiceBPOM.DataVaksin Vaksin, int StatusCode, string Message)
        {
            this.Vaksin = Vaksin;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrasiVaksinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrasiVaksinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool RegistrasiVaksinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public RegistrasiVaksinResponse()
        {
        }
        
        public RegistrasiVaksinResponse(bool RegistrasiVaksinResult, int StatusCode, string Message)
        {
            this.RegistrasiVaksinResult = RegistrasiVaksinResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LaporKedatanganVaksin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaporKedatanganVaksinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NoRegistrasiVaksin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public LaporKedatanganVaksinRequest()
        {
        }
        
        public LaporKedatanganVaksinRequest(string NoRegistrasiVaksin, int StatusCode, string Message)
        {
            this.NoRegistrasiVaksin = NoRegistrasiVaksin;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LaporKedatanganVaksinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaporKedatanganVaksinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LaporKedatanganVaksinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public LaporKedatanganVaksinResponse()
        {
        }
        
        public LaporKedatanganVaksinResponse(bool LaporKedatanganVaksinResult, int StatusCode, string Message)
        {
            this.LaporKedatanganVaksinResult = LaporKedatanganVaksinResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LaporPenggunaanVaksin", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaporPenggunaanVaksinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NoRegistrasiVaksin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string NIK;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int JumlahPakai;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Message;
        
        public LaporPenggunaanVaksinRequest()
        {
        }
        
        public LaporPenggunaanVaksinRequest(string NoRegistrasiVaksin, string NIK, int JumlahPakai, int StatusCode, string Message)
        {
            this.NoRegistrasiVaksin = NoRegistrasiVaksin;
            this.NIK = NIK;
            this.JumlahPakai = JumlahPakai;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LaporPenggunaanVaksinResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaporPenggunaanVaksinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LaporPenggunaanVaksinResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int StatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Message;
        
        public LaporPenggunaanVaksinResponse()
        {
        }
        
        public LaporPenggunaanVaksinResponse(bool LaporPenggunaanVaksinResult, int StatusCode, string Message)
        {
            this.LaporPenggunaanVaksinResult = LaporPenggunaanVaksinResult;
            this.StatusCode = StatusCode;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceBPOMChannel : ServiceBPOM.IServiceBPOM, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceBPOMClient : System.ServiceModel.ClientBase<ServiceBPOM.IServiceBPOM>, ServiceBPOM.IServiceBPOM
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBPOMClient() : 
                base(ServiceBPOMClient.GetDefaultBinding(), ServiceBPOMClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceBPOM.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBPOMClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBPOMClient.GetBindingForEndpoint(endpointConfiguration), ServiceBPOMClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBPOMClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBPOMClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBPOMClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBPOMClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBPOMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceBPOM.RegistrasiVaksinResponse ServiceBPOM.IServiceBPOM.RegistrasiVaksin(ServiceBPOM.RegistrasiVaksinRequest request)
        {
            return base.Channel.RegistrasiVaksin(request);
        }
        
        public bool RegistrasiVaksin(ServiceBPOM.DataVaksin Vaksin, ref int StatusCode, ref string Message)
        {
            ServiceBPOM.RegistrasiVaksinRequest inValue = new ServiceBPOM.RegistrasiVaksinRequest();
            inValue.Vaksin = Vaksin;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceBPOM.RegistrasiVaksinResponse retVal = ((ServiceBPOM.IServiceBPOM)(this)).RegistrasiVaksin(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.RegistrasiVaksinResult;
        }
        
        public System.Threading.Tasks.Task<ServiceBPOM.RegistrasiVaksinResponse> RegistrasiVaksinAsync(ServiceBPOM.RegistrasiVaksinRequest request)
        {
            return base.Channel.RegistrasiVaksinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceBPOM.LaporKedatanganVaksinResponse ServiceBPOM.IServiceBPOM.LaporKedatanganVaksin(ServiceBPOM.LaporKedatanganVaksinRequest request)
        {
            return base.Channel.LaporKedatanganVaksin(request);
        }
        
        public bool LaporKedatanganVaksin(string NoRegistrasiVaksin, ref int StatusCode, ref string Message)
        {
            ServiceBPOM.LaporKedatanganVaksinRequest inValue = new ServiceBPOM.LaporKedatanganVaksinRequest();
            inValue.NoRegistrasiVaksin = NoRegistrasiVaksin;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceBPOM.LaporKedatanganVaksinResponse retVal = ((ServiceBPOM.IServiceBPOM)(this)).LaporKedatanganVaksin(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.LaporKedatanganVaksinResult;
        }
        
        public System.Threading.Tasks.Task<ServiceBPOM.LaporKedatanganVaksinResponse> LaporKedatanganVaksinAsync(ServiceBPOM.LaporKedatanganVaksinRequest request)
        {
            return base.Channel.LaporKedatanganVaksinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceBPOM.LaporPenggunaanVaksinResponse ServiceBPOM.IServiceBPOM.LaporPenggunaanVaksin(ServiceBPOM.LaporPenggunaanVaksinRequest request)
        {
            return base.Channel.LaporPenggunaanVaksin(request);
        }
        
        public bool LaporPenggunaanVaksin(string NoRegistrasiVaksin, string NIK, int JumlahPakai, ref int StatusCode, ref string Message)
        {
            ServiceBPOM.LaporPenggunaanVaksinRequest inValue = new ServiceBPOM.LaporPenggunaanVaksinRequest();
            inValue.NoRegistrasiVaksin = NoRegistrasiVaksin;
            inValue.NIK = NIK;
            inValue.JumlahPakai = JumlahPakai;
            inValue.StatusCode = StatusCode;
            inValue.Message = Message;
            ServiceBPOM.LaporPenggunaanVaksinResponse retVal = ((ServiceBPOM.IServiceBPOM)(this)).LaporPenggunaanVaksin(inValue);
            StatusCode = retVal.StatusCode;
            Message = retVal.Message;
            return retVal.LaporPenggunaanVaksinResult;
        }
        
        public System.Threading.Tasks.Task<ServiceBPOM.LaporPenggunaanVaksinResponse> LaporPenggunaanVaksinAsync(ServiceBPOM.LaporPenggunaanVaksinRequest request)
        {
            return base.Channel.LaporPenggunaanVaksinAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBPOM))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBPOM))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/TrackingVaksinServices/ServiceBPOM.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceBPOMClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceBPOM);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceBPOMClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceBPOM);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceBPOM,
        }
    }
}
