//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking_Vaksin_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPenduduk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataPenduduk()
        {
            this.DataPasien = new HashSet<DataPasien>();
            this.Masyarakat = new HashSet<Masyarakat>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_pemerintah { get; set; }
        public string nama { get; set; }
        public string nik { get; set; }
        public string alamat { get; set; }
        public string jenis_kelamin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPasien> DataPasien { get; set; }
        public virtual Pemerintah Pemerintah { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masyarakat> Masyarakat { get; set; }
    }
}
