//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking_Vaksin_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataVaksin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataVaksin()
        {
            this.DataPasien = new HashSet<DataPasien>();
            this.RumahSakit = new HashSet<RumahSakit>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_produsen { get; set; }
        public string no_registrasi { get; set; }
        public string nama { get; set; }
        public Nullable<System.DateTime> tgl_pembuatan { get; set; }
        public Nullable<System.DateTime> tgl_terima { get; set; }
        public Nullable<int> jumlah { get; set; }
        public Nullable<int> jumlah_pakai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPasien> DataPasien { get; set; }
        public virtual Produsen Produsen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RumahSakit> RumahSakit { get; set; }
    }
}
