//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking_Vaksin_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataPasien
    {
        public int id { get; set; }
        public Nullable<int> id_penduduk { get; set; }
        public Nullable<int> id_rumahsakit { get; set; }
        public Nullable<int> id_vaksin { get; set; }
        public string nik { get; set; }
        public Nullable<System.DateTime> tgl_terimavaksin { get; set; }
    
        public virtual DataPenduduk DataPenduduk { get; set; }
        public virtual RumahSakit RumahSakit { get; set; }
        public virtual DataVaksin DataVaksin { get; set; }
    }
}
