//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking_Vaksin_Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBVaksinEntities : DbContext
    {
        public DBVaksinEntities()
            : base("name=DBVaksinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPOM> BPOM { get; set; }
        public virtual DbSet<DataPasien> DataPasien { get; set; }
        public virtual DbSet<DataPenduduk> DataPenduduk { get; set; }
        public virtual DbSet<DataVaksin> DataVaksin { get; set; }
        public virtual DbSet<Masyarakat> Masyarakat { get; set; }
        public virtual DbSet<Pemerintah> Pemerintah { get; set; }
        public virtual DbSet<Produsen> Produsen { get; set; }
        public virtual DbSet<RumahSakit> RumahSakit { get; set; }
    }
}
